# Generated by Django 4.2.4 on 2023-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150, verbose_name='название урока')),
                ('lesson_description', models.TextField(verbose_name='описание урока')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка')),
                ('lesson_video_reference', models.CharField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
