# Generated by Django 4.2.4 on 2023-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video_reference',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
